search_engine/urls.py
from django.urls import path

from . import views

app_name = 'search'
urlpatterns = [
	path('', views.index, name='index'),
	path('results/', views.results, name='results'),
	path('refresh/', views.refresh, name='refresh'),
	path('fetch_results/', views.fetch_results, name='fetch_results'),
]

torrent_search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('search/', include('search_engine.urls')),
    path('admin/', admin.site.urls),
]

search_engine/models.py
from django.db import models

class Category(models.Model):
	class Meta:
		ordering = ['name']

	category_id = models.IntegerField(default=0, primary_key=True)
	name = models.CharField(max_length=50)

class Tracker(models.Model):
	class Meta:
		ordering = ['title']
	
	tracker_id = models.CharField(max_length=50, primary_key=True)
	title = models.CharField(max_length=50)

class SearchEvent(models.Model):
	created_on = models.DateTimeField(auto_now_add=True)
	request = models.CharField(max_length=800)

	def set_request(self, x):
		self.request = json.dumps(x)

	def get_request(self):
		return json.loads(self.request)

class SearchRecord(models.Model):
	id = models.IntegerField(default=0, primary_key=True)
	age = models.DurationField(null=True)
	tracker_info = models.ForeignKey(Tracker, on_delete=models.CASCADE, null=True)
	name = models.CharField(max_length=200)
	size = models.BigIntegerField(default=0)
	category_info = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
	seeds = models.IntegerField(default=0)
	leechers = models.IntegerField(default=0)
	magnet = models.CharField(max_length=800)
	desc_url = models.CharField(max_length=800)
	search_event = models.ForeignKey(SearchEvent, db_column='search_event', on_delete=models.CASCADE, null=True)

search_engine/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.safestring import mark_safe

import xml.etree.ElementTree
from . import jackett_helper
from . import models
import json
import math
from datetime import datetime, timedelta
import pytz


# Helper Functions
def __hyperlink(link, text):
	return f'<a href="{link}">{text}</a>'

def __magnet(link):
	return f'<a href="{link}"><span class="fas fa-magnet"></span></a>'

def __search_record_result(sr):
	return [sr.id, sr.age.days if sr.age else 'Unknown', sr.tracker_info.title,
			 __hyperlink(sr.desc_url, sr.name), sr.size,
			sr.category_info.name, sr.seeds, sr.leechers, __magnet(sr.magnet)]

# View Functions
# /
def index(request):
	context = {'trackers': models.Tracker.objects.all(), 
				'cats': models.Category.objects.all()}
	
	return render(request, 'search_engine/index.html', context)

# /results/
def results(request):
	field_labels = ['ID', 'Age', 'Tracker', 'Title', 'Size', 
					'Category', 'Seeds', 'Leechers', 'Magnet']
	context = {'field_labels': field_labels, 
			'request': mark_safe(json.dumps(request.GET)),
			'query': request.GET['q']}

	return render(request, 'search_engine/results.html', context)

# /fetch_results/
def fetch_results(request):
	# Show Cached?
	_cached = request.GET.get('cached') == 'on'
	_request = dict(request.GET)
	if request.GET.get('cached'):
		del _request['cached']

	# Delete all old search events
	models.SearchEvent.objects.filter(created_on__lte=datetime.utcnow().replace(tzinfo=pytz.utc)
		- timedelta(days=1)).delete()
	
	_se = models.SearchEvent.objects.filter(request=_request).order_by('-created_on').first()
	if _se and _cached:
		context = {'results': [__search_record_result(x) for x in _se.searchrecord_set.all()]}
		return JsonResponse(context)

	search_results, se = jackett_helper.search(request)

	se.save()
	# models.SearchRecord.objects.all().delete()
	for _res in search_results:
		_sr = models.SearchRecord(**_res)
		# _sr.full_clean()
		_sr.save()

	context = {'results': [__search_record_result(x) for x in  se.searchrecord_set.all()]}

	return JsonResponse(context)

# /refresh/
@csrf_exempt
def refresh(request):
	# Clear existing trackers and re-populate
	models.Tracker.objects.all().delete()
	trackers = jackett_helper.get_trackers()
	for tracker_id, title in trackers.items():
		models.Tracker(tracker_id=tracker_id, title=title).save()

	# Clear existing Categories and re-populate
	models.Category.objects.all().delete()
	cats = jackett_helper.get_categories()
	for category_id, name in cats.items():
		models.Category(category_id=category_id, name=name).save()

	return HttpResponse('')

search_engine/templates/search_engine/index.html
<!DOCTYPE html>
<html lang="en" style="height: 100%; min-height: 100%;">
<head>
	<meta charset="utf-8">
	<title>Jackett Search Engine</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

	<script>
	$(document).ready(function() {
		$("#refresh").click(function (event) {
			$.ajax({
				url: "{% url 'search:refresh' %}",
				method : 'POST'
			}); 
		});
	});
</script>
</head>

<body style="height: 100%; min-height: 100%;">
	<div class="container d-flex align-items-center justify-content-center h-100">
		<div class="w-100">
			<h1 class="text-center pb-3"> Torrent Search </h1>
			<form class="pt-3" action="{% url 'search:results' %}" method="get">
				<div class="form-group">
					<label for="query">Query</label>
					<input class="form-control form-control-lg" type="text" id="query" name="q">

					<div class="form-row pt-3">
						<div class="form-group col-md-4">
							<div class="input-group w-100">
								<div class="input-group-prepend">
									<label class="input-group-text" for="tracker">Tracker</label>
								</div>
								<select class="selectpicker form-control" id="tracker" name="tracker" data-live-search="true">
									<option value="all" selected>All</option>
									{% for tracker in trackers %}
									<option value={{tracker.tracker_id}}>{{tracker.title}}</option>
									{% endfor %}
								</select>
							</div>
						</div>
						<div class="form-group col-md-4">
							<div class="input-group w-100">
								<div class="input-group-prepend">
									<label class="input-group-text" for="cat">Category</label>
								</div>

								<select class="selectpicker form-control" id="cat" name="cat" multiple data-live-search="true" data-actions-box="true">
									<option value="all" selected>All</option>
									{% for cat in cats %}
									<option value={{cat.category_id}}>{{cat.name}}</option>
									{% endfor %}
								</select>
							</div>
						</div>
						<div class="form-group col-md-2">
							<div class="input-group w-100">
								<div class="input-group-prepend">
									<label class="input-group-text" for="limit">Limit</label>
								</div>

								<input class="form-control" type="number" id="limit" name="limit" value="100" min="0" max="1000" step="10"/>
							</div>
						</div>
						<div class="form-check col-md-2 d-flex align-items-center justify-content-center pb-2">
							<div class="checkbox">
								<label><input class="mr-2" type="checkbox" id="cached" name="cached">Show Cached Results</label>
							</div>
						</div>
					</div>
				</div>

				<div class="w-100 text-center">
					<button type="submit" class="btn btn-primary"><span class="fas fa-search"></span>Search</button>
					<a href="#" class="btn btn-info" id="refresh"><span class="fas fa-sync"></span>Refresh Trackers</a>
				</div>
			</form>
		</div>
	</div>
</body>
</html>

search_engine/templates/search_engine/results.html
<!DOCTYPE html>
<html lang="en" style="height: 100%; min-height: 100%;">
<head>
	<meta charset="utf-8">
	<title>Results for {{query}}</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4-4.1.1/jq-3.3.1/dt-1.10.20/datatables.min.css"/>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/v/bs4-4.1.1/jq-3.3.1/dt-1.10.20/datatables.min.js"></script>
	<script>
		var __multiplier_prefix = {0: '', 10: 'K', 20: 'M', 30: 'G', 40: 'T'}
		function hr_size(size) {
			mul = Math.min(Math.floor(Math.log2(size)/10) * 10, 40)
			return (size / (2 ** mul)).toFixed(2) + ' ' + __multiplier_prefix[mul] + 'B'
		}

		$.fn.dataTable.ext.search.push(
		    function(settings, data, dataIndex) {
		        var max = parseInt( $('#max_age').val(), 10);
		        var age = parseFloat(data[1]) || 0;

		        if (isNaN(max) || age <= max)
		            return true;

		        return false;
		    }
		);

		$.fn.dataTable.ext.search.push(
		    function(settings, data, dataIndex) {
		        var min = parseInt( $('#min_seeds').val(), 10);
		        var seeds = parseFloat(data[6]) || 0;

		        if (isNaN(min) || seeds >= min)
		            return true;

		        return false;
		    }
		);

		$.fn.dataTable.ext.search.push(
		    function(settings, data, dataIndex) {
		    	var min = parseFloat( $('#min_size').val(), 10) * (2 ** $('#min_size_mul').val());
		        var max = parseFloat( $('#max_size').val(), 10) * (2 ** $('#max_size_mul').val());
		        var size = parseInt(data[4]) || 0;

		        if ( (isNaN(min) && isNaN(max)) || (isNaN(min) && size <= max) ||
             			(min <= size && isNaN(max)) || (min <= size && size <= max) )
		            return true;

		        return false;
		    }
		);

		$(document).ready(function() {
			var search_results = []
			var results_table = $('#results').DataTable({
				dom: 't  <"row view-pager"  <"col-md-4 d-flex align-items-center"  l>  <"col-md-4 d-flex justify-content-center align-items-center" p>  <"col-md-4 d-flex justify-content-end align-items-center"  i>  >',
				columns: [
					{% for label in field_labels %}
					{ title: "{{label}}" },
					{% endfor %}
				],
				columnDefs: [
					{
						targets: 1,
						render: function (data, type, row, meta) {
							if (type === 'display')
								data = data + ' days';
							return data;
						}
					},
					{
						targets: 4,
						render: function (data, type, row, meta) {
							if (type === 'display')
								data = hr_size(data);
							return data;
						}
					}
				],
				data: search_results,
				pageLength: 25
			});

			function on_filter_field_change() {
	    		results_table.column(3).search($('#search_title').val())
	        	results_table.draw();
			}

		    $('#max_age, #search_title, #min_size, #max_size, #min_seeds').keyup(on_filter_field_change);

		    $('#min_size_mul, #max_size_mul').change(on_filter_field_change)

			$.ajax({
				url: "{% url 'search:fetch_results' %}",
				method: 'GET',
				data: {{request}},
				success: function(response) {
					search_results = response.results;

					$('#loading').remove();
					$('#content').removeClass("d-none");
					$('#content').removeClass("d-md-none");

					$('#results_length > label').addClass("mb-0");
					$('#results_info').addClass("pt-0")

					results_table.clear();
					results_table.rows.add(search_results);
					results_table.columns.adjust().draw();
				}
			});
		});
	</script>
</head>

<body style="height: 100%; min-height: 100%;">
	<div class="container d-flex h-100 align-items-center justify-content-center" id="loading">
		<div class="spinner-grow text-primary" role="status">
			<span class="sr-only">Loading...</span>
		</div>
		<div class="spinner-grow text-secondary" role="status">
			<span class="sr-only">Loading...</span>
		</div>
		<div class="spinner-grow text-success" role="status">
			<span class="sr-only">Loading...</span>
		</div>
		<div class="spinner-grow text-danger" role="status">
			<span class="sr-only">Loading...</span>
		</div>
		<div class="spinner-grow text-warning" role="status">
			<span class="sr-only">Loading...</span>
		</div>
		<div class="spinner-grow text-info" role="status">
			<span class="sr-only">Loading...</span>
		</div>
		<div class="spinner-grow text-dark" role="status">
			<span class="sr-only">Loading...</span>
		</div>
	</div>

	<div class="container-fluid d-flex justify-content-center mt-3 mb-3 d-none d-md-none" id="content">
		<div class="container col-md-12">
			<div class="form-inline">
				<div class="col-md-2">
					<label class="sr-only" for="max_age">Max. Age (days)</label>
		 			<input type="text" class="form-control" id="max_age"  placeholder="Max. Age (days)">
		 		</div>

		 		<div class="col-md-2">
		 			<label class="sr-only" for="search_title">Refine Search</label>
		 			<input type="text" class="form-control" id="search_title"  placeholder="Refine Search">
		 		</div>

	 			<div class="col-md-2">
		 			<label class="sr-only" for="min_size">Min. Size</label>
		 			<input type="text" class="form-control" id="min_size"  placeholder="Min. Size">
		 		</div>

				<div class="col-md-1">
		 			<select class="selectpicker form-control" id="min_size_mul" data-live-search="true">
						<option value="10">KB</option>
						<option value="20" selected>MB</option>
						<option value="30">GB</option>
						<option value="40">TB</option>
					</select>
				</div>

	 			<div class="col-md-2">
		 			<label class="sr-only" for="max_size">Max. Size</label>
		 			<input type="text" class="form-control" id="max_size"  placeholder="Max. Size">
		 		</div>

	 			<div class="col-md-1">
		 			<select class="selectpicker form-control" id="max_size_mul" data-live-search="true">
						<option value="10">KB</option>
						<option value="20" selected>MB</option>
						<option value="30">GB</option>
						<option value="40">TB</option>
					</select>
				</div>

	 			<div class="col-md-2">
		 			<label class="sr-only" for="min_seeds">Min. Seeds</label>
		 			<input type="text" class="form-control" id="min_seeds"  placeholder="Min. Seeds">
		 		</div>
			</div>
			<table class="table table-hover w-100" id="results">
				<thead thead-dark></thead>
				<tbody>
					{% for r in results %}
					<tr>
						<td>{{r.id}}</td>
						<td>{{r.age.days}} days</td>
						<td>{{r.tracker_info.title}}</td>
						<td>{{r.name}}</td>
						<td>{{r.size}}</td>
						<td>{{r.category_info.name}}</td>
						<td>{{r.seeds}}</td>
						<td>{{r.leechers}}</td>
						<td><a href="{{r.magnet}}">Magnet</a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</body>
</html>